# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 550)
        MainWindow.setMinimumSize(QtCore.QSize(550, 550))
        MainWindow.setMaximumSize(QtCore.QSize(3000, 3000))
        MainWindow.setStyleSheet("background-color: rgb(150, 255, 160)")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMinimumSize(QtCore.QSize(550, 550))
        self.centralWidget.setStyleSheet("background-color: rgb(150, 255, 160);\n"
"border: 1px solid rgb(170, 85, 255);")
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"background-color: rgb(150, 255, 160);\n"
"height: 25px; width: 150px;\n"
"border: 1px solid rgb(170, 85, 255);\n"
"color: rgb(85, 0, 127);\n"
" }\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"background-color: rgb(80, 255, 50);\n"
"}\n"
"QTabWidget::Pane { \n"
"background-color: rgb(80, 255, 50);\n"
"}\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.test = QtWidgets.QWidget()
        self.test.setStyleSheet("color: rgb(85, 0, 127);\n"
"")
        self.test.setObjectName("test")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.test)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.test)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.test)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 3, 1, 1)
        self.t_labs = QtWidgets.QListView(self.test)
        self.t_labs.setObjectName("t_labs")
        self.gridLayout_5.addWidget(self.t_labs, 1, 0, 2, 1)
        self.t_tests = QtWidgets.QListView(self.test)
        self.t_tests.setObjectName("t_tests")
        self.gridLayout_5.addWidget(self.t_tests, 1, 1, 1, 2)
        self.t_result = QtWidgets.QListView(self.test)
        self.t_result.setObjectName("t_result")
        self.gridLayout_5.addWidget(self.t_result, 1, 3, 2, 1)
        self.start_all = QtWidgets.QPushButton(self.test)
        self.start_all.setAutoDefault(False)
        self.start_all.setDefault(False)
        self.start_all.setFlat(False)
        self.start_all.setObjectName("start_all")
        self.gridLayout_5.addWidget(self.start_all, 2, 1, 1, 1)
        self.start_current = QtWidgets.QPushButton(self.test)
        self.start_current.setEnabled(False)
        self.start_current.setAutoDefault(False)
        self.start_current.setObjectName("start_current")
        self.gridLayout_5.addWidget(self.start_current, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.test)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 1, 1, 2)
        self.gridLayout_5.setColumnStretch(0, 2)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_5.setColumnStretch(3, 2)
        self.tabWidget.addTab(self.test, "")
        self.manual = QtWidgets.QWidget()
        self.manual.setStyleSheet("color: rgb(85, 0, 127);\n"
"")
        self.manual.setObjectName("manual")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.manual)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.manual)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.manual)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 1, 1, 1)
        self.m_labs = QtWidgets.QListView(self.manual)
        self.m_labs.setObjectName("m_labs")
        self.gridLayout_4.addWidget(self.m_labs, 1, 0, 3, 1)
        self.m_tests = QtWidgets.QListView(self.manual)
        self.m_tests.setObjectName("m_tests")
        self.gridLayout_4.addWidget(self.m_tests, 1, 1, 3, 1)
        self.m_test = QtWidgets.QListView(self.manual)
        self.m_test.setObjectName("m_test")
        self.gridLayout_4.addWidget(self.m_test, 1, 2, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.manual)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 2, 2, 1, 2)
        self.clear = QtWidgets.QPushButton(self.manual)
        self.clear.setObjectName("clear")
        self.gridLayout_4.addWidget(self.clear, 3, 2, 1, 1)
        self.m_save = QtWidgets.QPushButton(self.manual)
        self.m_save.setObjectName("m_save")
        self.gridLayout_4.addWidget(self.m_save, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.manual)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 2, 1, 2)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setColumnStretch(2, 2)
        self.gridLayout_4.setColumnStretch(3, 2)
        self.gridLayout_4.setRowStretch(2, 100)
        self.tabWidget.addTab(self.manual, "")
        self.autotest = QtWidgets.QWidget()
        self.autotest.setStyleSheet("color: rgb(85, 0, 127);\n"
"")
        self.autotest.setObjectName("autotest")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.autotest)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.autotest)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.autotest)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.a_labs = QtWidgets.QListView(self.autotest)
        self.a_labs.setObjectName("a_labs")
        self.gridLayout_2.addWidget(self.a_labs, 1, 0, 3, 1)
        self.a_tests = QtWidgets.QListView(self.autotest)
        self.a_tests.setObjectName("a_tests")
        self.gridLayout_2.addWidget(self.a_tests, 1, 1, 3, 1)
        self.a_test = QtWidgets.QListView(self.autotest)
        self.a_test.setObjectName("a_test")
        self.gridLayout_2.addWidget(self.a_test, 1, 2, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.autotest)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 2, 1, 2)
        self.a_clear = QtWidgets.QPushButton(self.autotest)
        self.a_clear.setObjectName("a_clear")
        self.gridLayout_2.addWidget(self.a_clear, 3, 2, 1, 1)
        self.a_save = QtWidgets.QPushButton(self.autotest)
        self.a_save.setObjectName("a_save")
        self.gridLayout_2.addWidget(self.a_save, 3, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.autotest)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.gridLayout_2.setColumnStretch(3, 2)
        self.tabWidget.addTab(self.autotest, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 595, 19))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "List of labs"))
        self.label_3.setText(_translate("MainWindow", "Results"))
        self.start_all.setText(_translate("MainWindow", "Start All"))
        self.start_current.setText(_translate("MainWindow", "Start Current"))
        self.label_2.setText(_translate("MainWindow", "List of tests"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test), _translate("MainWindow", "Testing"))
        self.label_7.setText(_translate("MainWindow", "List of labs"))
        self.label_8.setText(_translate("MainWindow", "List of tests"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.m_save.setText(_translate("MainWindow", "Save"))
        self.label_9.setText(_translate("MainWindow", "New test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manual), _translate("MainWindow", "Manual Test Creator"))
        self.label_10.setText(_translate("MainWindow", "List of labs"))
        self.label_11.setText(_translate("MainWindow", "List of tests"))
        self.a_clear.setText(_translate("MainWindow", "Clear"))
        self.a_save.setText(_translate("MainWindow", "Save"))
        self.label_12.setText(_translate("MainWindow", "New test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.autotest), _translate("MainWindow", "Automatic Test Creator"))

